git-big-picture/git-big-picture

git-big-picture

Add filter option -c/-C to include commit message on labels.
This is a modified version from @jkoepcke that takes your comments into account.
Fixes #16.

Add commit msg on label

---

git-big-picture

@zapp42 I cleaned up some things from #31 - can you check them?

Cleanup commit messages feature

---

git-big-picture
test.scf

Fix including commit messages (regression from #48)

---

README.rst
git-big-picture
test.scf

Based on (a rebased version of) pull request #25 by @fredden

Stop leaving temp files behind (finishes up on #25)

---

.coveragerc
.github/workflows/run-tests.yml
.gitignore
run-tests-with-coverage.sh
test_requirements.txt

~Sits on top of #50 to avoid conflicts for the moment.~

Start measuring code coverage

---

README.rst
git-big-picture

~Sits on top of pull request #49 to avoid conflicts. Happy to rebase off of it, once #49 is merged to master, if you prefer.~

Migrate from optparse to argparse

---

README.rst

@esc just an idea, what do you think?

Readme: Improve section on people involved

---

git-big-picture

@esc the diff display up here makes a bit hard to see what `git show -w` makes great to see:
The second commit does *a lot less* than GitHub makes it look like…

Handle Ctrl+C gracefully

---

git-big-picture

- Old: `/tmp/git-big-picturenbgfl2y6.svg`
- New: `/tmp/git-big-picture-nbgfl2y6.svg`

Improve tempfile prefix

---

README.rst
run-tests-with-coverage.sh
test.py
test_requirements.txt

Replace nose by pytest for a test runner (fixes #63)

---

README.rst
git-big-picture
test.scf

Fixes issue #36, related to pull request #35
~Sits on top of #54 (and #49) to avoid conflicts for the moment. Happy to add tests after #50 is merged.~

Support history directions other than upwards (fixes #36, related to #35)

---

README.rst

remove TODO from README

---

.github/workflows/run-tests.yml
test.cram

.. so that they are more self-contained and work out of the box in more environments.

Move Git user setup into Cram tests (to make them work better outside of CI)

---

.style.yapf

Related:
https://github.com/hartwork/wnpp.debian.net/pull/15

yapf: Re-configure formatting of dictionaries

---

git_big_picture/_main.py

Fixes #156
https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements
CC @elfring

_main.py: Make use of augmented assignment statements (fixes #156)

---

README.rst
git-big-picture.1
git_big_picture/_main.py

@esc could be controversial, but may be a good move. What do you think?

Switch default history direction from upwards to rightwards

---

README.rst

@esc this is in preparation of a new release 1.2.0. It's the only key thing I found since v1.1.1 that deserves mention.

README.rst: Add #162 to change log

---

README.rst
git-big-picture.1
git_big_picture/_main.py
setup.py
test.py
test_requirements.txt

Simplify graph using Graphviz filter "tred" (fixes #180)

---

test.cram

Related:
https://lists.gnu.org/archive/html/info-gnu/2022-09/msg00001.html

Resolve use of deprecated "fgrep" by "grep -F"

---

.pre-commit-config.yaml
git_big_picture/_main.py

pre-commit: Migrate pyupgrade to Python >=3.9 (follow-up to #478)
